# 1. Euler Method

In [21]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
def EulerMethod(a,b,c,N,f):
#     h = (b-a)/N
    x = np.linspace(a,b,N+1)
    h = x[1] - x[0]
    y = np.zeros(N+1) 
#     y = np.zeros(len(x)) 
    y[0] = c
    for i in range(0,N):
        y[i+1] = y[i] + h*f(y[i],x[i])
    return y

In [32]:
def EulerMethod1(f,c,t):

    h = t[1] - t[0]
    y = np.zeros(len(t)) 
#     y = np.zeros(len(x)) 
    y[0] = c
    for i in range(0,len(t)-1):
        y[i+1] = y[i] + h*f(y[i],t[i])
    return y

In [35]:
a = 0
b = 1
c = 1/9
N = 100

def f(y,x):
    return np.exp(x)/(3+6*np.exp(x))

# g = lambda y,x: np.exp(x)/(3+6*np.exp(x))


EulerMethod(a,b,c,N,f)

array([0.11111111, 0.11222222, 0.11333703, 0.11445552, 0.11557769,
       0.11670352, 0.11783299, 0.1189661 , 0.12010282, 0.12124316,
       0.12238709, 0.1235346 , 0.12468568, 0.12584031, 0.12699849,
       0.12816019, 0.1293254 , 0.13049411, 0.13166631, 0.13284197,
       0.1340211 , 0.13520366, 0.13638965, 0.13757906, 0.13877187,
       0.13996805, 0.14116761, 0.14237053, 0.14357678, 0.14478636,
       0.14599924, 0.14721542, 0.14843489, 0.14965761, 0.15088359,
       0.1521128 , 0.15334522, 0.15458086, 0.15581967, 0.15706167,
       0.15830681, 0.1595551 , 0.16080652, 0.16206105, 0.16331867,
       0.16457936, 0.16584313, 0.16710994, 0.16837978, 0.16965263,
       0.17092849, 0.17220733, 0.17348913, 0.17477389, 0.17606159,
       0.1773522 , 0.17864572, 0.17994213, 0.18124141, 0.18254354,
       0.18384852, 0.18515631, 0.18646692, 0.18778032, 0.1890965 ,
       0.19041543, 0.19173711, 0.19306151, 0.19438863, 0.19571845,
       0.19705094, 0.1983861 , 0.1997239 , 0.20106434, 0.20240

In [34]:
t = np.linspace(a,b,N+1)
EulerMethod1(f,c,t)

array([0.11111111, 0.11222222, 0.11333703, 0.11445552, 0.11557769,
       0.11670352, 0.11783299, 0.1189661 , 0.12010282, 0.12124316,
       0.12238709, 0.1235346 , 0.12468568, 0.12584031, 0.12699849,
       0.12816019, 0.1293254 , 0.13049411, 0.13166631, 0.13284197,
       0.1340211 , 0.13520366, 0.13638965, 0.13757906, 0.13877187,
       0.13996805, 0.14116761, 0.14237053, 0.14357678, 0.14478636,
       0.14599924, 0.14721542, 0.14843489, 0.14965761, 0.15088359,
       0.1521128 , 0.15334522, 0.15458086, 0.15581967, 0.15706167,
       0.15830681, 0.1595551 , 0.16080652, 0.16206105, 0.16331867,
       0.16457936, 0.16584313, 0.16710994, 0.16837978, 0.16965263,
       0.17092849, 0.17220733, 0.17348913, 0.17477389, 0.17606159,
       0.1773522 , 0.17864572, 0.17994213, 0.18124141, 0.18254354,
       0.18384852, 0.18515631, 0.18646692, 0.18778032, 0.1890965 ,
       0.19041543, 0.19173711, 0.19306151, 0.19438863, 0.19571845,
       0.19705094, 0.1983861 , 0.1997239 , 0.20106434, 0.20240

In [38]:
def RangeKutta2(a,b,c,N,f):
#     h = (b-a)/N
    x = np.linspace(a,b,N+1)
    h = x[1] - x[0]
    y = np.zeros(N+1) 
#     y = np.zeros(len(x)) 
    y[0] = c
    for i in range(0,N):
        k1 = h*f(y[i],x[i])
        k2 = h*f(y[i]+k1,x[i]+h)
        y[i+1] = y[i] + (1/2)*(k1+k2)
    return y

In [39]:
RangeKutta2(a,b,c,N,f)

array([0.11111111, 0.11222407, 0.11334072, 0.11446105, 0.11558505,
       0.1167127 , 0.11784399, 0.1189789 , 0.12011744, 0.12125957,
       0.12240529, 0.12355458, 0.12470744, 0.12586384, 0.12702378,
       0.12818724, 0.1293542 , 0.13052465, 0.13169858, 0.13287598,
       0.13405682, 0.1352411 , 0.1364288 , 0.13761991, 0.1388144 ,
       0.14001228, 0.14121351, 0.1424181 , 0.14362601, 0.14483724,
       0.14605178, 0.1472696 , 0.14849069, 0.14971504, 0.15094264,
       0.15217345, 0.15340748, 0.15464471, 0.15588512, 0.15712869,
       0.1583754 , 0.15962526, 0.16087823, 0.1621343 , 0.16339346,
       0.16465569, 0.16592098, 0.1671893 , 0.16846065, 0.169735  ,
       0.17101235, 0.17229267, 0.17357596, 0.17486218, 0.17615134,
       0.1774434 , 0.17873837, 0.18003621, 0.18133692, 0.18264047,
       0.18394686, 0.18525606, 0.18656807, 0.18788285, 0.18920041,
       0.19052071, 0.19184376, 0.19316952, 0.19449798, 0.19582914,
       0.19716296, 0.19849944, 0.19983856, 0.20118031, 0.20252

In [40]:
def RangeKutta4(a,b,c,N,f):
#     h = (b-a)/N
    x = np.linspace(a,b,N+1)
    h = x[1] - x[0]
    y = np.zeros(N+1) 
#     y = np.zeros(len(x)) 
    y[0] = c
    for i in range(0,N):
        k1 = h*f(y[i],x[i])
        k2 = h*f(y[i]+(k1/2),x[i]+(h/2))
        k3 = h*f(y[i]+(k2/2),x[i]+(h/2))
        k4 = h*f(y[i]+k3,x[i]+h)
        y[i+1] = y[i] + (1/6)*(k1+2*k2+2*k3+k4)
    return y

In [42]:
RangeKutta4(a,b,c,N,f)

array([0.11111111, 0.11222407, 0.11334072, 0.11446106, 0.11558505,
       0.1167127 , 0.11784399, 0.11897891, 0.12011744, 0.12125958,
       0.1224053 , 0.1235546 , 0.12470745, 0.12586386, 0.1270238 ,
       0.12818725, 0.12935422, 0.13052467, 0.1316986 , 0.132876  ,
       0.13405685, 0.13524113, 0.13642883, 0.13761993, 0.13881443,
       0.14001231, 0.14121354, 0.14241813, 0.14362604, 0.14483728,
       0.14605181, 0.14726964, 0.14849073, 0.14971508, 0.15094268,
       0.1521735 , 0.15340753, 0.15464475, 0.15588516, 0.15712873,
       0.15837545, 0.15962531, 0.16087828, 0.16213435, 0.16339351,
       0.16465574, 0.16592103, 0.16718936, 0.16846071, 0.16973506,
       0.17101241, 0.17229274, 0.17357602, 0.17486225, 0.1761514 ,
       0.17744347, 0.17873844, 0.18003628, 0.18133699, 0.18264055,
       0.18394693, 0.18525614, 0.18656814, 0.18788293, 0.18920049,
       0.19052079, 0.19184384, 0.1931696 , 0.19449807, 0.19582922,
       0.19716305, 0.19849953, 0.19983865, 0.2011804 , 0.20252

In [14]:
def EulerMethodSyst(a,b,c,N,f):
#     h = (b-a)/N
    t = np.linspace(a,b,N+1)
    h = t[1] - t[0]
    z = np.zeros((N+1,len(c))) 
#     y = np.zeros(len(x)) 
    z[0,] = c
    for i in range(0,N):
        z[i+1,] = z[i,] + h*f(z[i,],t[i])
    return z

In [15]:
def f(z,t):
    x = z[0]
    y = z[1]
    dx = 3*x - 2*y
    dy = 2*x - 2*y
    return np.array([dx,dy])
a = 0
b = 1
c = np.array([1,0])
N = 200

EulerMethodSyst(a,b,c,N,f)

array([[1.        , 0.        ],
       [1.015     , 0.01      ],
       [1.030125  , 0.02005   ],
       [1.04537638, 0.03015075],
       [1.06075551, 0.04030301],
       [1.07626382, 0.05050753],
       [1.0919027 , 0.06076509],
       [1.10767359, 0.07107647],
       [1.12357793, 0.08144244],
       [1.13961717, 0.0918638 ],
       [1.15579279, 0.10234133],
       [1.17210627, 0.11287584],
       [1.1885591 , 0.12346815],
       [1.20515281, 0.13411906],
       [1.22188891, 0.1448294 ],
       [1.23876895, 0.15559999],
       [1.25579449, 0.16643168],
       [1.27296709, 0.17732531],
       [1.29028834, 0.18828173],
       [1.30775985, 0.19930179],
       [1.32538323, 0.21038637],
       [1.34316011, 0.22153634],
       [1.36109215, 0.23275258],
       [1.37918101, 0.24403598],
       [1.39742836, 0.25538743],
       [1.41583591, 0.26680783],
       [1.43440537, 0.27829812],
       [1.45313847, 0.28985919],
       [1.47203696, 0.30149198],
       [1.49110259, 0.31319743],
       [1.

In [17]:
def RangeKutta2Syst(a,b,c,N,f):
#     h = (b-a)/N
    t = np.linspace(a,b,N+1)
    h = t[1] - t[0]
    z = np.zeros((N+1,len(c))) 
#     y = np.zeros(len(x)) 
    z[0,] = c
    for i in range(0,N):
        k1 = h*f(z[i,],t[i])
        k2 = h*f(z[i,]+k1,t[i]+h)
        z[i+1] = z[i,] + (1/2)*(k1+k2)
    return z

In [18]:
RangeKutta2Syst(a,b,c,N,f)

array([[1.        , 0.        ],
       [1.0150625 , 0.010025  ],
       [1.03025138, 0.02010075],
       [1.04556803, 0.03022801],
       [1.06101386, 0.04040755],
       [1.0765903 , 0.05064014],
       [1.09229877, 0.06092656],
       [1.10814073, 0.07126759],
       [1.12411765, 0.08166402],
       [1.14023099, 0.09211666],
       [1.15648225, 0.10262631],
       [1.17287293, 0.11319378],
       [1.18940456, 0.1238199 ],
       [1.20607867, 0.13450548],
       [1.22289682, 0.14525136],
       [1.23986055, 0.15605839],
       [1.25697147, 0.16692741],
       [1.27423115, 0.17785927],
       [1.29164122, 0.18885485],
       [1.3092033 , 0.199915  ],
       [1.32691902, 0.21104061],
       [1.34479006, 0.22223257],
       [1.36281808, 0.23349177],
       [1.38100477, 0.2448191 ],
       [1.39935184, 0.25621548],
       [1.41786102, 0.26768183],
       [1.43653404, 0.27921907],
       [1.45537266, 0.29082813],
       [1.47437866, 0.30250996],
       [1.49355383, 0.31426551],
       [1.

In [19]:
def RangeKutta4Syst(a,b,c,N,f):
#     h = (b-a)/N
    t = np.linspace(a,b,N+1)
    h = t[1] - t[0]
    z = np.zeros((N+1,len(c))) 
#     y = np.zeros(len(x)) 
    z[0,] = c
    for i in range(0,N):
        k1 = h*f(z[i,],t[i])
        k2 = h*f(z[i,]+(k1/2),t[i]+(h/2))
        k3 = h*f(z[i,]+(k2/2),t[i]+(h/2))
        k4 = h*f(z[i,]+k3,t[i]+h)
        z[i+1] = z[i,] + (1/6)*(k1+2*k2+2*k3+k4)
    return z

In [20]:
RangeKutta4Syst(a,b,c,N,f)

array([[1.        , 0.        ],
       [1.01506273, 0.01002513],
       [1.03025184, 0.020101  ],
       [1.04556873, 0.0302284 ],
       [1.06101481, 0.04040807],
       [1.07659149, 0.05064079],
       [1.09230022, 0.06092734],
       [1.10814244, 0.07126851],
       [1.12411961, 0.08166509],
       [1.14023322, 0.09211787],
       [1.15648475, 0.10262766],
       [1.17287571, 0.11319528],
       [1.18940762, 0.12382155],
       [1.20608202, 0.13450728],
       [1.22290046, 0.14525332],
       [1.23986449, 0.1560605 ],
       [1.25697571, 0.16692968],
       [1.27423571, 0.17786171],
       [1.29164609, 0.18885745],
       [1.30920849, 0.19991778],
       [1.32692454, 0.21104356],
       [1.34479591, 0.22223569],
       [1.36282426, 0.23349506],
       [1.3810113 , 0.24482258],
       [1.39935872, 0.25621914],
       [1.41786825, 0.26768568],
       [1.43654164, 0.2792231 ],
       [1.45538063, 0.29083236],
       [1.474387  , 0.30251438],
       [1.49356255, 0.31427013],
       [1.